<<<<<<< HEAD

# Generated by Django 5.1 on 2024-08-23 13:45
=======
# Generated by Django 5.1 on 2024-08-23 15:40
>>>>>>> c8abbf7a8c967b8fb453e61d0be3605b20ba4fc8

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('finishDate', models.DateField()),
                ('items', models.JSONField(default=dict)),
                ('place', models.CharField(max_length=50)),
                ('orderNumber', models.TextField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
