# Generated by Django 5.1 on 2024-08-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalform',
            name='items',
            field=models.JSONField(default=dict),
        ),
    ]
