# Generated by Django 5.1 on 2024-08-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rentalform_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalform',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
