<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-08-23 15:41
=======
# Generated by Django 5.1 on 2024-08-23 15:42
>>>>>>> b420bfb4be7b534413af5e424edf24326b9becd1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rentalform_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalform',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
