# Generated by Django 5.1 on 2024-08-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rentalform_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalform',
            name='place',
        ),
    ]
