# Generated by Django 5.0.7 on 2024-08-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rentalform_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalform',
            name='place',
        ),
        migrations.AddField(
            model_name='rentalform',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
